### ISSUE TITLE
 About Japanese correspondence

### ISSUE THREAD

**Issue by kdogi** [EricZimmerman/WxTCmd#1]
Hi, Eric.
Thank you for the useful tool.
I'm verifying ActivitiesCache.db on my PC.
However, when WxTCmd is used, all the Japanese part in the created tsv file becomes "?".
Are there any good methods or plans for improvement?
If possible, it will be helpful if you can correspond to Japanese.
(I am using Google translation because I can not speak English.)

**Comment by EricZimmerman** [comment]
私は日本語を話さないので、これもgoogle翻訳です

私はCSVファイルをUnicodeエンコーディングに変更したので、v0.3.1.0を試してみてください

I do not speak Japanese, so this is also google translate

Try v0.3.1.0 as I changed the CSV files to Unicode encoding
