### ISSUE TITLE
About AppActivityId

### ISSUE THREAD

**Issue by kdogi** [EricZimmerman/WxTCmd#4]
I am studying Windows 10 Timeline using this tool.

In the tsv file extracted using this tool, if you open a file with the same file name on the same day, only the first time is recorded in the payload column. As I confirmed, the file name of the original DB was listed only in the payload column for the first time. Since I think that it is all described in the AppActivityId column, can you get it and display it?

Regards,

This text uses Google's translation.

**Comment by EricZimmerman** [comment]
i need more info on this. like a sample database illustrating the problem. will close for now, but if you can give me a test case i can take a look
